export const UPDATE_VIDEO_METADATA = 'UPDATE_VIDEO_METADATA';
export const REMOVE_VIDEO_METADATA = 'REMOVE_VIDEO_METADATA';
export const SHOW_MINIPLAYER = 'SHOW_MINIPLAYER';
export const HIDE_MINIPLAYER = 'HIDE_MINIPLAYER';
